version: '1.0'
services:
    testing:
        environment:
            - TOKEN=YOUR_DISCORD_BOT_TOKEN
            - OWNER_ID=DISCORDID_OF_BOTOWNER
            - SUPPORT_SERVER=DISCORD-ID-SUPPORTSERVER
        restart: always
        image: 'serpensin/discord_webhook_creator'
        container_name: 'WebhookCreator'