version: '1.0'
services:
    testing:
        environment:
            - TOKEN=YOUR_DISCORD_BOT_TOKEN
            - OWNER_ID=DISCORDID_OF_BOTOWNER
            - SUPPORT_SERVER=DISCORD-ID-SUPPORTSERVER
            - LOG_LEVEL=INFO
        restart: always
        image: ghcr.io/serpensin/discordbots-webhookcreator:latest
        container_name: 'WebhookCreator'
        ports:
            - '5000:5000'
        volumes:
            - data:/app/WH-Creator/Logs
        healthcheck:
          test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
          interval: 30s
          timeout: 10s
          retries: 3
          start_period: 20s

volumes:
    data: